name: Playwright Tests

on: [push, pull_request]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-playwright-container .

    - name: Run Playwright tests
      run: docker run --rm my-playwright-container

    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: playwright-report
